In [1]:
from keras.models import load_model
import matplotlib.pyplot as plt
import numpy as np
import time
import pandas as pd
from sklearn.model_selection import train_test_split
from IPython.display import display

df = pd.read_csv('data/bootstrap.csv', index_col=0)
df_e10 = pd.read_csv('data/e10.csv', index_col=0)
df_e12 = pd.read_csv('data/e12.csv', index_col=0)
# display(df)



Using TensorFlow backend.


In [2]:
predictors = [x for x in df.columns if x not in ['label_name', 'label']]
X = df[predictors]
y = df.label
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [3]:
print('loading autoencoder')
t0 = time.time()
autoencoder = load_model('autoencoder.h5')
t1 = time.time()
print('Model loaded in: ', t1-t0)

loading autoencoder
('Model loaded in: ', 10.421329021453857)


In [6]:
def denoise(x):
    print x.shape
    denoised_x = autoencoder.predict(x)
    print denoised_x.shape
    return denoised_x
denoised_X = denoise(X.values) #e10 e12.5 not same dimension as given data

(309, 20713)
(309, 20713)


In [16]:
df_denoise = pd.DataFrame(data=denoised_X,columns=predictors)
display(df_denoise)
# width = 20
# height = 12
# hist = X.iloc[:,0:4]
# plt.figure(figsize=(width, height))
# hist.plot.kde()

# hist_denoise = df_denoise.iloc[:,0:4]
# hist_denoise.plot.kde()
# plt.show()

0610005C13Rik  0610007P14Rik  0610009B22Rik  0610009L18Rik  \
0              0.0            0.0            0.0            0.0   
1              0.0            0.0            0.0            0.0   
2              0.0            0.0            0.0            0.0   
3              0.0            0.0            0.0            0.0   
4              0.0            0.0            0.0            0.0   
5              0.0            0.0            0.0            0.0   
6              0.0            0.0            0.0            0.0   
7              0.0            0.0            0.0            0.0   
8              0.0            0.0            0.0            0.0   
9              0.0            0.0            0.0            0.0   
10             0.0            0.0            0.0            0.0   
11             0.0            0.0            0.0            0.0   
12             0.0            0.0            0.0            0.0   
13             0.0            0.0            0.0            0.0   
14             0.0            0.0            0.0            0.0   
15             0.0            0.0            0.0            0.0   
16             0.0            0.0            0.0            0.0   
17             0.0            0.0            0.0            0.0   
18             0.0            0.0            0.0            0.0   
19             0.0            0.0            0.0            0.0   
20             0.0            0.0            0.0            0.0   
21             0.0            0.0            0.0            0.0   
22             0.0            0.0            0.0            0.0   
23             0.0            0.0            0.0            0.0   
24             0.0            0.0            0.0            0.0   
25             0.0            0.0            0.0            0.0   
26             0.0            0.0            0.0            0.0   
27             0.0            0.0            0.0            0.0   
28             0.0            0.0            0.0            0.0   
29             0.0            0.0            0.0            0.0   
..             ...            ...            ...            ...   
279            0.0            0.0            0.0            0.0   
280            0.0            0.0            0.0            0.0   
281            0.0            0.0            0.0            0.0   
282            0.0            0.0            0.0            0.0   
283            0.0            0.0            0.0            0.0   
284            0.0            0.0            0.0            0.0   
285            0.0            0.0            0.0            0.0   
286            0.0            0.0            0.0            0.0   
287            0.0            0.0            0.0            0.0   
288            0.0            0.0            0.0            0.0   
289            0.0            0.0            0.0            0.0   
290            0.0            0.0            0.0            0.0   
291            0.0            0.0            0.0            0.0   
292            0.0            0.0            0.0            0.0   
293            0.0            0.0            0.0            0.0   
294            0.0            0.0            0.0            0.0   
295            0.0            0.0            0.0            0.0   
296            0.0            0.0            0.0            0.0   
297            0.0            0.0            0.0            0.0   
298            0.0            0.0            0.0            0.0   
299            0.0            0.0            0.0            0.0   
300            0.0            0.0            0.0            0.0   
301            0.0            0.0            0.0            0.0   
302            0.0            0.0            0.0            0.0   
303            0.0            0.0            0.0            0.0   
304            0.0            0.0            0.0            0.0   
305            0.0            0.0            0.0            0.0   
306            0.0            0.0            0.0    

In [11]:
# y_train = y_train.ravel()
print X_train.shape, X_test.shape
print y_train.shape, y_test.shape

display(X_train)

(247, 20713) (62, 20713)
(247,) (62,)


0610005C13Rik  0610007P14Rik  0610009B22Rik  0610009L18Rik  \
126      19.010669    2672.369124     200.539209      46.284444   
109      17.993730    2620.220632     205.052139      34.117605   
247      22.239503     970.897139     351.931957     154.905482   
234      -4.465644    1135.471174    1079.602236     219.145205   
202      17.692148    2874.049152     208.928354      38.199257   
78       10.727676     574.699736     120.270153      21.341766   
147      26.709476    2188.414976     204.712721      28.040498   
59        2.022352     552.293259     349.269412      21.411418   
118      24.277643    1890.371441     204.329085      31.534932   
6        21.000000    1145.000000     355.000000      33.000000   
182      23.694257    2717.976139     204.436376      30.673149   
30        2.456113     502.333891      62.282983      10.950838   
22       -1.565078     379.520461      20.261030      18.989752   
262      35.578799     764.808286     899.929074     285.596547   
56       -3.208533     333.760809     380.343585      16.468696   
148      26.075668    2964.410597     203.021655      27.790525   
140      31.636699    2130.332186     209.427779      25.576199   
208      20.410779    2435.237384     212.074279      40.126879   
277      15.882664    1252.171713     968.877687      20.469251   
203      19.318351    2436.182318     199.725924      39.209787   
144      33.015328    2026.208176     213.077457      39.403206   
167      22.397679    1912.396574     214.006064      42.802660   
90       -1.270117     145.011605     492.490087      12.514271   
223       8.875183     711.940481     536.849212     298.599551   
66        0.699475     510.195953     650.341175      15.407781   
116      18.573791    2312.497557     205.654752      47.549841   
172      17.560293    2166.307716     210.109705      36.782018   
250      30.158671    1014.511780    1037.723994      98.903445   
19        4.870099     450.410608     165.506738      18.255072   
146      22.583470    2715.292463     212.556970      16.778622   
..             ...            ...            ...            ...   
50        2.417557     637.722091     396.919198      14.811174   
174      19.394827    1798.761424     203.330876      30.792396   
189      18.000641    2205.898886     210.121415      40.421664   
307      17.783485     875.758253     719.894720     220.977809   
187      19.036128    1571.356841     207.137846      28.334011   
169      22.001228    2142.977461     212.520643      41.396138   
58       10.272264     433.651343     188.372502      12.968136   
48        4.686295     195.346084     376.419824      30.719788   
235      14.036077    1238.750780       3.825198       5.334234   
252      20.499320    1324.532697     283.126893     173.833990   
21        4.338095     111.737032     461.196947      14.009425   
160      14.368275    2831.723571     209.676335      29.126428   
276      17.203811     745.623248     702.563987     171.341053   
191      18.128761    3374.747752     211.210172      41.361448   
293      14.790884    1073.536626     734.589410      -2.166437   
257       4.160301     249.446969      88.662268     293.059724   
149      24.186663    1896.017335     207.571303      41.024850   
130      27.155666    2066.552294     205.708903      34.660747   
151      26.525293    2861.526150     203.290337      39.429247   
99        3.637164     191.565799     493.094663      22.629645   
87        8.260946     325.018516     437.813742      12.461885   
214      19.162962     599.304647     266.692585     -63.429336   
121      36.517526    1753.832587     206.130742      45.658701   
308      19.462925     465.292187     747.026337      -3.026093   
20        2.931366     590.782891     180.784073      21.776004   
188      32.475903    2430.072857     212.535650      34.650549   
71        3.979638     706.980628     -15.123676      16.524647   
106       1.260537     522.906185     466.609270    

In [14]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()
clf.fit(X_train, y_train)

GaussianNB(priors=None)

In [15]:
y_predict = clf.predict(X_test)
display(y_predict)
print("Test Accuracy [%0.3f]" % ((y_test == y_predict).mean()))
print np.unique(y_predict)

array([ 3.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  3.,  1.,  1.,  2.,  3.,
        3.,  3.,  3.,  3.,  2.,  2.,  2.,  1.,  1.,  2.,  2.,  1.,  2.,
        2.,  1.,  3.,  3.,  1.,  2.,  1.,  3.,  1.,  1.,  1.,  1.,  2.,
        2.,  1.,  1.,  2.,  3.,  3.,  2.,  3.,  3.,  3.,  1.,  2.,  3.,
        2.,  1.,  2.,  3.,  3.,  2.,  2.,  3.,  3.,  2.])

Test Accuracy [1.000]
[ 1.  2.  3.]


In [23]:

clf.fit(X, y)
predictions = clf.predict_proba(df_e12.values)

In [25]:
display(predictions)

array([[  1.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  1.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  1.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  1.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  1.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  1.99847625e-255,   0.00000000e+000,   1.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   1.00000000e+000],
       [  1.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  1.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  1.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   1.00000000e+000],
       [  1.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  1.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  1.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  1.00000000e+000,   0.00000000e+000,   0.00000000e+000],
       [  

In [28]:
df_e12_labels = pd.read_csv('data/e12_labels.csv', index_col=0)
df_e12_labels.label.unique()

array(['progenitor', 'neuron', 'adipo.dermal', 'myogenic'], dtype=object)

In [ ]:
# labels [1,2,3] = 'bulk_neuralTube1', 'bulk_BAT1', 'bulk_muscle1 = mygenic'